# Generated by Django 4.2.7 on 2023-11-16 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreria_antisocial', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bajo',
            name='activo_o_pasivo',
        ),
    ]
