# Generated by Django 4.2.7 on 2023-11-28 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria_antisocial', '0002_remove_bajo_activo_o_pasivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuitarraElectrica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=50)),
                ('numero_cuerdas', models.PositiveIntegerField()),
            ],
        ),
    ]
